export const LAY_DS_CHUYEN_BAY = "LAY_DS_CHUYEN_BAY"
export const LAY_DS_CHUYEN_BAY_SUCCESS = "LAY_DS_CHUYEN_BAY_SUCCESS"
export const LAY_DS_CHUYEN_BAY_FAIL = "LAY_DS_CHUYEN_BAY_FAIL"
export const SELECTED_FILTERS = "SELECTED_FILTERS"
export const CHUYEN_BAY_DI_DA_CHON = "CHUYEN_BAY_DI_DA_CHON"
export const CHUYEN_BAY_VE_DA_CHON = "CHUYEN_BAY_VE_DA_CHON"
export const HANH_KHACH_NGUOI_LON = "HANH_KHACH_NGUOI_LON"
export const HANH_KHACH_TRE_EM = "HANH_KHACH_TRE_EM"
export const HANH_KHACH_EM_BE = "HANH_KHACH_EM_BE"
export const THONG_TIN_HANH_KHACH = "THONG_TIN_HANH_KHACH"
export const SELECT_SEAT = "SELECT_SEAT"
export const LAY_DS_GHE_CHUYEN_DI_VJ = "LAY_DS_GHE_CHUYEN_DI_VJ"
export const LAY_DS_GHE_CHUYEN_DI_VJ_SUCCESS = "LAY_DS_GHE_CHUYEN_DI_VJ_SUCCESS"
export const LAY_DS_GHE_CHUYEN_VE_VJ = "LAY_DS_GHE_CHUYEN_VE_VJ"
export const LAY_DS_GHE_CHUYEN_VE_VJ_SUCCESS = "LAY_DS_GHE_CHUYEN_VE_VJ_SUCCESS"
export const DAT_VE_VJ = "DAT_VE_VJ"
export const DAT_VE_VJ_SUCCESS = "DAT_VE_VJ_SUCCESS"
export const TINH_PHI_VE = "TINH_PHI_VE"
export const TINH_PHI_VE_SUCCESS = "TINH_PHI_VE_SUCCESS"
export const LAY_DS_GHE_CHUYEN_DI_BB = "LAY_DS_GHE_CHUYEN_DI_BB"
export const LAY_DS_GHE_CHUYEN_DI_BB_SUCCESS = "LAY_DS_GHE_CHUYEN_DI_BB_SUCCESS"
export const XAC_NHAN_GIA_VE_BB = "XAC_NHAN_GIA_VE_BB"
export const XAC_NHAN_GIA_VE_BB_SUCCESS = "XAC_NHAN_GIA_VE_BB_SUCCESS"
export const DAT_VE_BB = "DAT_VE_BB"
export const DAT_VE_BB_SUCCESS = "DAT_VE_BB_SUCCESS"
export const THEM_VE_VAO_DAT_CHO = "THEM_VE_VAO_DAT_CHO"
export const THEM_VE_VAO_DAT_CHO_SUCCESS = "THEM_VE_VAO_DAT_CHO_SUCCESS"
export const BO_QUA_DAT_CHO = "BO_QUA_DAT_CHO"
export const BO_QUA_DAT_CHO_SUCCESS = "BO_QUA_DAT_CHO_SUCCESS"
export const THEM_HANH_KHACH_VAO_VE = "THEM_HANH_KHACH_VAO_VE"
export const THEM_HANH_KHACH_VAO_VE_SUCCESS = "THEM_HANH_KHACH_VAO_VE_SUCCESS"
export const DAT_VE_VN = "DAT_VE_VN"
export const DAT_VE_VN_SUCCESS = "DAT_VE_VN_SUCCESS"
export const XUAT_VE_VJ = "XUAT_VE_VJ"
export const XUAT_VE_VJ_SUCCESS = "XUAT_VE_VJ_SUCCESS"
export const TINH_PHI_VE_CHON_GHE = "TINH_PHI_VE_CHON_GHE"
export const TINH_PHI_VE_CHON_GHE_SUCCESS = "TINH_PHI_VE_CHON_GHE_SUCCESS"
export const SAVE_NAME_SEAT_CHOOSE_MOT_CHIEU = "SAVE_NAME_SEAT_CHOOSE_MOT_CHIEU"
export const SAVE_ARR_SEAT_CHOOSE_MOT_CHIEU = "SAVE_ARR_SEAT_CHOOSE_MOT_CHIEU"
export const SAVE_AFTER_ARR_SEAT_CHOOSE_MOT_CHIEU = "SAVE_AFTER_ARR_SEAT_CHOOSE_MOT_CHIEU"
export const SAVE_NAME_SEAT_CHOOSE_HAI_CHIEU = "SAVE_NAME_SEAT_CHOOSE_HAI_CHIEU"
export const SAVE_ARR_SEAT_CHOOSE_HAI_CHIEU = "SAVE_ARR_SEAT_CHOOSE_HAI_CHIEU"
export const SAVE_AFTER_ARR_SEAT_CHOOSE_HAI_CHIEU = "SAVE_AFTER_ARR_SEAT_CHOOSE_HAI_CHIEU"
export const LAY_DANH_SACH_PHU_TRO_CHUYEN_DI = "LAY_DANH_SACH_PHU_TRO_CHUYEN_DI"
export const LAY_DANH_SACH_PHU_TRO_CHUYEN_DI_SUCCESS = "LAY_DANH_SACH_PHU_TRO_CHUYEN_DI_SUCCESS"
export const LAY_DANH_SACH_PHU_TRO_CHUYEN_VE = "LAY_DANH_SACH_PHU_TRO_CHUYEN_VE"
export const LAY_DANH_SACH_PHU_TRO_CHUYEN_VE_SUCCESS = "LAY_DANH_SACH_PHU_TRO_CHUYEN_VE_SUCCESS"
export const SAVE_DATA_PHU_TRO_CHUYEN_DI_VJ = "SAVE_DATA_PHU_TRO_CHUYEN_DI_VJ"
export const SAVE_DATA_PHU_TRO_CHUYEN_VE_VJ = "SAVE_DATA_PHU_TRO_CHUYEN_VE_VJ"
export const SAVE_DATA_PHU_TRO_THUC_AN_VJ_DI = "SAVE_DATA_PHU_TRO_THUC_AN_VJ_DI"
export const SAVE_DATA_PHU_TRO_THUC_AN_VJ_VE = "SAVE_DATA_PHU_TRO_THUC_AN_VJ_VE"
export const GET_DS_BAO_HIEM_VJ_CHUYEN_DI = "GET_DS_BAO_HIEM_VJ_CHUYEN_DI"
export const GET_DS_BAO_HIEM_VJ_CHUYEN_DI_SUCCESS = "GET_DS_BAO_HIEM_VJ_CHUYEN_DI_SUCCESS"
export const GET_DS_BAO_HIEM_VJ_CHUYEN_VE = "GET_DS_BAO_HIEM_VJ_CHUYEN_VE"
export const GET_DS_BAO_HIEM_VJ_CHUYEN_VE_SUCCESS = "GET_DS_BAO_HIEM_VJ_CHUYEN_VE_SUCCESS"
export const SAVE_NAME_BAO_HIEM_MOT_CHIEU = "SAVE_NAME_BAO_HIEM_MOT_CHIEU"
export const SAVE_NAME_BAO_HIEM_HAI_CHIEU = "SAVE_NAME_BAO_HIEM_HAI_CHIEU"
export const SAVE_ARR_BAO_HIEM_MOT_CHIEU = "SAVE_ARR_BAO_HIEM_MOT_CHIEU"
export const SAVE_ARR_BAO_HIEM_HAI_CHIEU = "SAVE_ARR_BAO_HIEM_HAI_CHIEU"
export const LAY_DS_PHU_TRO_CHUYEN_DI_BB = "LAY_DS_PHU_TRO_CHUYEN_DI_BB"
export const LAY_DS_PHU_TRO_CHUYEN_DI_BB_SUCCESS = "LAY_DS_PHU_TRO_CHUYEN_DI_BB_SUCCESS"
export const LAY_DS_PHU_TRO_CHUYEN_VE_BB = "LAY_DS_PHU_TRO_CHUYEN_VE_BB"
export const LAY_DS_PHU_TRO_CHUYEN_VE_BB_SUCCESS = "LAY_DS_PHU_TRO_CHUYEN_VE_BB_SUCCESS"
export const LAY_DS_HANH_LY_CHUYEN_DI_BB = "LAY_DS_HANH_LY_CHUYEN_DI_BB"
export const LAY_DS_HANH_LY_CHUYEN_DI_BB_SUCCESS = "LAY_DS_HANH_LY_CHUYEN_DI_BB_SUCCESS"
export const LAY_DS_HANH_LY_CHUYEN_VE_BB = "LAY_DS_HANH_LY_CHUYEN_VE_BB"
export const LAY_DS_HANH_LY_CHUYEN_VE_BB_SUCCESS = "LAY_DS_HANH_LY_CHUYEN_VE_BB_SUCCESS"
export const SAVE_DATA_HANH_LY_CHUYEN_DI = "SAVE_DATA_HANH_LY_CHUYEN_DI"
export const SAVE_DATA_HANH_LY_CHUYEN_VE = "SAVE_DATA_HANH_LY_CHUYEN_VE"





































