
const TaskActionTypes = {
  //báo giá thay đổi thông tin
  CAP_NHAT_BAO_GIA_HANH_KHACH: "CAP_NHAT_BAO_GIA_HANH_KHACH",
  CAP_NHAT_BAO_GIA_HANH_KHACH_SUCCESS: "CAP_NHAT_BAO_GIA_HANH_KHACH_SUCCESS",
  CAP_NHAT_BAO_GIA_HANH_KHACH_FAIL: "CAP_NHAT_BAO_GIA_HANH_KHACH_FAIL",

  //cập nhật hành khách
  CAP_NHAT_THONG_TIN_HANH_KHACH: "CAP_NHAT_THONG_TIN_HANH_KHACH",
  CAP_NHAT_THONG_TIN_HANH_KHACH_SUCCESS: "CAP_NHAT_THONG_TIN_HANH_KHACH_SUCCESS",
  CAP_NHAT_THONG_TIN_HANH_KHACH_FAIL: "CAP_NHAT_THONG_TIN_HANH_KHACH_FAIL",

  // lấy thông tin hành khách bb
  LAY_THONG_TIN_HANH_KHACH_BB: "LAY_THONG_TIN_HANH_KHACH_BB",
  LAY_THONG_TIN_HANH_KHACH_BB_SUCCESS: "LAY_THONG_TIN_HANH_KHACH_BB_SUCCESS",
  LAY_THONG_TIN_HANH_KHACH_BB_FAIL: "LAY_THONG_TIN_HANH_KHACH_BB_FAIL",

  //post thông tin hành khách
  POST_THONG_TIN_HANH_KHACH: "POST_THONG_TIN_HANH_KHACH",
  POST_THONG_TIN_HANH_KHACH_SUCCESS: "POST_THONG_TIN_HANH_KHACH_SUCCESS",
  POST_THONG_TIN_HANH_KHACH_FAIL: "POST_THONG_TIN_HANH_KHACH_FAIL",

  //Cập nhật phí thay đổi thông tin
  CAP_NHAT_PHI_THAY_DOI: "CAP_NHAT_PHI_THAY_DOI",
  CAP_NHAT_PHI_THAY_DOI_SUCCESS: "CAP_NHAT_PHI_THAY_DOI_SUCCESS",
  CAP_NHAT_PHI_THAY_DOI_FAIL: "CAP_NHAT_PHI_THAY_DOI_FAIL",

  //lưu thông tin tính phí
  SAVE_DATA_FORM: "SAVE_DATA_FORM"
}

export default TaskActionTypes;
