
const TaskActionTypes = {
  // lấy danh sách đã chọn
  LAY_DS_DAT_CHO_DA_CHON: "LAY_DS_DAT_CHO_DA_CHON",
  LAY_DS_DAT_CHO_DA_CHON_SUCCESS: "LAY_DS_DAT_CHO_DA_CHON_SUCCESS",
  LAY_DS_DAT_CHO_DA_CHON_FAIL: "LAY_DS_DAT_CHO_DA_CHON_FAIL",

  //xuất vé
  POST_XUAT_VE: "POST_XUAT_VE",
  POST_XUAT_VE_SUCCESS: "POST_XUAT_VE_SUCCESS",
  POST_XUAT_VE_FAIL: "POST_XUAT_VE_FAIL",

  //xuất vé bb
  POST_XUAT_VE_BB: "POST_XUAT_VE_BB",
  POST_XUAT_VE_BB_SUCCESS: "POST_XUAT_VE_BB_SUCCESS",
  POST_XUAT_VE_BB_FAIL: "POST_XUAT_VE_BB_FAIL",

  //lấy thông tin giá vé
  LAY_THONG_TIN_GIA_VE: "LAY_THONG_TIN_GIA_VE",
  LAY_THONG_TIN_GIA_VE_SUCCESS: "LAY_THONG_TIN_GIA_VE_SUCCESS",
  LAY_THONG_TIN_GIA_VE_FAIL: "LAY_THONG_TIN_GIA_VE_FAIL",

  LAY_THONG_TIN_PHI_VE: "LAY_THONG_TIN_PHI_VE",
  LAY_THONG_TIN_PHI_VE_SUCCESS: "LAY_THONG_TIN_PHI_VE_SUCCESS",
  LAY_THONG_TIN_PHI_VE_FAIL: "LAY_THONG_TIN_PHI_VE_FAIL"
}

export default TaskActionTypes;
