
const TaskActionTypes = {
  // lấy danh sách
  GET_CHARTS_DATA: "GET_CHARTS_DATA",
  GET_CHARTS_DATA_SUCCESS: "GET_CHARTS_DATA_SUCCESS",
  GET_CHARTS_DATA_FAIL: "GET_CHARTS_DATA_FAIL",

  /* ORDERS */
  GET_ORDERS: "GET_ORDERS",
  GET_ORDERS_SUCCESS: "GET_ORDERS_SUCCESS",
  GET_ORDERS_FAIL: "GET_ORDERS_FAIL",

}

export default TaskActionTypes;
