
const TaskActionTypes = {
  // lấy danh sách tỉnh
  LAY_DS_TINH: "LAY_DS_TINH",
  LAY_DS_TINH_SUCCESS: "LAY_DS_TINH_SUCCESS",
  LAY_DS_TINH_FAIL: "LAY_DS_TINH_FAIL",
  // lấy danh sách khu vực
  LAY_DS_KHU_VUC: "LAY_DS_KHU_VUC",
  LAY_DS_KHU_VUC_SUCCESS: "LAY_DS_KHU_VUC_SUCCESS",
  LAY_DS_KHU_VUC_FAIL: "LAY_DS_KHU_VUC_FAIL",
  // lấy danh sách quốc gia
  LAY_DS_QUOC_GIA: "LAY_DS_QUOC_GIA",
  LAY_DS_QUOC_GIA_SUCCESS: "LAY_DS_QUOC_GIA_SUCCESS",
  LAY_DS_QUOC_GIA_FAIL: "LAY_DS_QUOC_GIA_FAIL",
  // lấy danh sách sân bay
  LAY_DS_SAN_BAY: "LAY_DS_SAN_BAY",
  LAY_DS_SAN_BAY_SUCCESS: "LAY_DS_SAN_BAY_SUCCESS",
  LAY_DS_SAN_BAY_FAIL: "LAY_DS_SAN_BAY_FAIL",
}

export default TaskActionTypes;
