
const TaskActionTypes = {
  LAY_DS_CHUYEN_BAY_MOI: "LAY_DS_CHUYEN_BAY_MOI",
  LAY_DS_CHUYEN_BAY_MOI_SUCCESS: "LAY_DS_CHUYEN_BAY_MOI_SUCCESS",
  LAY_DS_CHUYEN_BAY_MOI_FAIL: "LAY_DS_CHUYEN_BAY_MOI_FAIL",

   //báo giá thay đổi thông tin
  CAP_NHAT_BAO_GIA_HANH_TRINH: "CAP_NHAT_BAO_GIA_HANH_TRINH",
  CAP_NHAT_BAO_GIA_HANH_TRINH_SUCCESS: "CAP_NHAT_BAO_GIA_HANH_TRINH_SUCCESS",
  CAP_NHAT_BAO_GIA_HANH_TRINH_FAIL: "CAP_NHAT_BAO_GIA_HANH_TRINH_FAIL",

  CAP_NHAT_THEM_CHANG: "CAP_NHAT_THEM_CHANG",
  CAP_NHAT_THEM_CHANG_SUCCESS: "CAP_NHAT_THEM_CHANG_SUCCESS",
  CAP_NHAT_THEM_CHANG_FAIL: "CAP_NHAT_THEM_CHANG_FAIL",
  
  //Cập nhật phí thay đổi thông tin
  CAP_NHAT_PHI_THAY_DOI: "CAP_NHAT_PHI_THAY_DOI",
  CAP_NHAT_PHI_THAY_DOI_SUCCESS: "CAP_NHAT_PHI_THAY_DOI_SUCCESS",
  CAP_NHAT_PHI_THAY_DOI_FAIL: "CAP_NHAT_PHI_THAY_DOI_FAIL",

}

export default TaskActionTypes;
